apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-3jfq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-3jfq
    app.kubernetes.io/part-of: component-annotation-dotnet-component
  name: devfile-sample-dotnet60-basic-3jfq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-3jfq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-3jfq
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rs-demos-yqsg-tenant/component-annotation-dotnet-component/devfile-sample-dotnet60-basic-3jfq@sha256:a46689038851ffbc31aed3f6787194f7399d946ddfb2e6bd3cb4a29f1cb404ca
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
